# Development override for docker-compose.yml
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DEBUG=True
      - LOG_LEVEL=DEBUG
    volumes:
      # Mount source code for hot reload
      - .:/app
      - /app/__pycache__
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--log-level", "debug"]
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=smsproj_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dev_password

  redis:
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass dev_password

# Remove nginx in development
profiles:
  - development