name: Simple Deploy Check

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Basic syntax check
      run: |
        python -m py_compile main.py
        python -c "from main import app; print('✅ App imports successfully')"

    - name: Check database script
      run: |
        python -c "import create_admin_user; print('✅ Admin user script ready')"

    - name: Build status
      run: |
        echo "✅ Build successful - ready for Render deployment"
        echo "🔑 Login credentials: admin@cumapp.com / admin123"